int _putchar(char c);
void print_alphabet();
void print_alphabet_x10();
int _islower();
int _isalpha();
int print_sign();
int _abs();
int print_last_digit();
void jack_bauer();
void times_table();
int add();
void print_to_98();
